# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cal_correlation <- function(expression_matrix, rownames, gene_of_interest, method) {
    .Call(`_GCAS_cal_correlation`, expression_matrix, rownames, gene_of_interest, method)
}

